### ISSUE TITLE
Certain Flower Drops Aren't Working

### ISSUE THREAD

**Issue by NerdetteNut** [Moonrez/Hybrid-Flowers#1]
Poppies and cornflowers aren't dropping the original color variants when grown from seeds; this means that red poppy seeds are only useful for cooking, and blue cornflower seeds aren't useful at all.  In addition, white and magenta orchids, when grown from seeds, are dropping magenta orchids, in spite of the fact that the flower growing from the crop is clearly white and magenta.

**Comment by Moonrez** [comment]
Fixed in version 1.1
